### ISSUE TITLE
Links to images break due to case sensitivity mismatch

### ISSUE THREAD

**Issue by lucas42** [Financial-Times/express-markdown-pages#2]
When embedding an image, its filename gets converted to lowercase.  Embedding that path in the markdown automatically gets converted, however links to the same image don't.

Example:
```
[![Deciding which authentication to use](authentication/images/Authentication-Decision-Tree.png)](authentication/images/Authentication-Decision-Tree.png)
```
- the image gets embedded correctly, however when clicking on it, hits a 404.

**Comment by i-like-robots** [comment]
This needs to check if a link is to an image, not just another page: https://github.com/Financial-Times/express-markdown-pages/blob/main/lib/markdown/HTMLRenderer.js#L57
