### ISSUE TITLE
Sorting files by a date prefix

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/express-markdown-pages#5]
The ability to present an ordered lists of pages is driven by the logic which parses the filename prefixes.

Currently the filename parsing logic is restricted to parsing for integers which end in a dot.

It would great if that logic could be extended to allow dates. e.g. `2021-06-24. Todays Blog` as a filename would trigger the extraction of 26/4/2021 as a sortable date in the `order` field.

**Comment by GeoffThorpeFT** [comment]
It would be even better if the extended parse/extract logic could, on detection of a date filename prefix, also set a `frontmatter` property named `date` to the same value.  That would avoid the need to explicitly store the date within the file.

**Comment by wheresrhys** [comment]
I think we get by fine without this
