### ISSUE TITLE
Add ability to disable `o-syntax-highlighter`

### ISSUE THREAD

**Issue by paulrobertlloyd** [Financial-Times/express-markdown-pages#6]
Great project – does exactly what I was looking for, and in a really smart and intuitive way. I have one suggestion, although appreciate this is in the spirit of making this project work better for those not using Origami/working within the FT…

Currently Markdown is rendered with code blocks decorated using the wrapping `div` and hooks required by `o-syntax-highlight`. For example:

~~~
```js
console.log('hello, world!')
```
~~~

is rendered as:

```html
<div data-o-component="o-syntax-highlight">
  <pre><code class="o-syntax-highlight--js">console.log('hello, world!')</code></pre>
</div>
```

If however you want to use another highlighting tool, the required hooks are no longer present. Ideally the output would be something more along the lines of this:

```html
<pre><code class="language-js">console.log('hello, world!')</code></pre>
```

This being a class hook supported by [Prism.js](https://prismjs.com) and [Highlighter.js](https://prismjs.com)

Happy for the default to remain such that `o-syntax-highlight` is preferred, it’d just be useful to be able to disable this somehow.

**Comment by wheresrhys** [comment]
Open to a pull request if you really want this feature, but it's under active development so we will probably never get round to implementing it

**Comment by paulrobertlloyd** [comment]
I actually got around this on my project by using the undecorated plain text string, then rendering it using my own Markdown renderer. Was really great to have that option available 🙂
